// made by tools/gen_sim_ports.py
wire [45:0] HPS_BUS;
wire  CLK_VIDEO;
wire  CE_PIXEL;
wire [12:0] VIDEO_ARX;
wire [12:0] VIDEO_ARY;
wire [7:0] VGA_R;
wire [7:0] VGA_G;
wire [7:0] VGA_B;
wire  VGA_HS;
wire  VGA_VS;
wire  VGA_DE;
wire  VGA_F1;
wire [1:0] VGA_SL;
wire  VGA_SCALER;
wire  VGA_DISABLE;
wire [11:0] HDMI_WIDTH = 0;
wire [11:0] HDMI_HEIGHT = 0;
wire  HDMI_FREEZE;
wire  HDMI_BLACKOUT;
wire  HDMI_BOB_DEINT;
wire  LED_USER;
wire [1:0] LED_POWER;
wire [1:0] LED_DISK;
wire [1:0] BUTTONS;
wire  CLK_AUDIO = 0;
wire [15:0] AUDIO_L;
wire [15:0] AUDIO_R;
wire  AUDIO_S;
wire [1:0] AUDIO_MIX;
wire [3:0] ADC_BUS;
wire  SD_SCK;
wire  SD_MOSI;
wire  SD_MISO = 0;
wire  SD_CS;
wire  SD_CD = 0;
wire  DDRAM_CLK;
wire  DDRAM_BUSY = 0;
wire [7:0] DDRAM_BURSTCNT;
wire [28:0] DDRAM_ADDR;
wire [63:0] DDRAM_DOUT = 0;
wire  DDRAM_DOUT_READY = 0;
wire  DDRAM_RD;
wire [63:0] DDRAM_DIN;
wire [7:0] DDRAM_BE;
wire  DDRAM_WE;
wire  SDRAM_CLK;
wire  SDRAM_CKE;
wire [12:0] SDRAM_A;
wire [1:0] SDRAM_BA;
wire [15:0] SDRAM_DQ;
wire  SDRAM_DQML;
wire  SDRAM_DQMH;
wire  SDRAM_nCS;
wire  SDRAM_nCAS;
wire  SDRAM_nRAS;
wire  SDRAM_nWE;
wire  UART_CTS = 0;
wire  UART_RTS;
wire  UART_RXD = 0;
wire  UART_TXD;
wire  UART_DTR;
wire  UART_DSR = 0;
wire [6:0] USER_IN = 0;
wire [6:0] USER_OUT;
wire  OSD_STATUS = 0;
